---
title: "α-diveristy"
output: html_notebook
---

```{r}
library(dplyr)
taxa_isol <- med %>% 
  select(Order, Isolationsource, Currentname) %>% 
  filter(Isolationsource != "") %>% 
  group_by(Isolationsource) %>% 
  summarize(Number_taxa = n(), Taxa_percent = (Number_taxa/604) * 100) %>% 
  arrange(desc(Number_taxa))
```

```{r}
med <- read.csv("../Data/New_med_list.csv")
```

#Build a treemap for each Country

```{r}
library(bdvis)

s <- split(med, med$Country)

taxtree <- med %>% 
  select(Order, Family, Genustotal, Country) %>% 
  filter(Order != " ") 

tmtu <- taxotree(taxtree, title = "Treemap Turkey", legend = "Number of Families in Turkey", sum1 = "Family", sum2 = "Genustotal")

taxtree <- med %>% 
  select(Order, Family, Genustotal, Country) %>% 
  filter(Country == "Egypt") %>% 
  taxotree(n = 30, title = "Treemap Egypt Turkey", legend = "Number of Families in Egypt", sum1 = "Family", sum2 = "Genustotal")

taxtree <- med %>% 
  select(Order, Family, Genustotal, Country) %>% 
  filter(Country == "Greece") %>% 
  taxotree(n = 30, title = "Treemap Greece", legend = "Number of Families in Greece", sum1 = "Family", sum2 = "Genustotal")

```

```{r}
ord <- med %>% select(Order, Family, Genustotal) %>% 
  filter(Order != " ") %>% 
  group_by(Order, Family, Genustotal) %>% 
  summarize(N = n(), Percent = N/4828*100)
ord <- ord[-c(1:2),]
ord


tr <- taxotree(ord, n = 30, title = "Order records", sum1 = "Family", sum2 = "Genustotal")
  

```

```{r}
format_bdvis(med, source = NULL, config = NULL, quiet = FALSE, gettaxo = TRUE)
bdsummary(med)

colnames(med)

#Rename column where name is Currentname
names(med)[names(med) == "Currentname"] <- "Scientific_name"
med
#Convert variable Scientific_name to character
med$Scientific_name <- as.character(med$Scientific_name)
class(med$Scientific_name)

#Retrieve higher taxonomy information for each record from EOL
gettaxo(med, genus = FALSE, verbose = TRUE, progress = TRUE)
```

```{r}

```



