---
title: "R Notebook"
output: html_notebook
---



```{r}
med <- read.csv("../Data/New_med_list.csv")
med
library(tidyverse)
```

```{r}
install.packages("ggThemeAssist")
library(ggThemeAssist)
```

#Barplot with records for each year

```{r}
#Convert the column Year to character
med$Year <- as.character(as.numeric(med$Year))

#Reorder variable Year using dplyr function
#mutate(name = fct_reorder(as.factor(Year), Count))
med$Title

ye <- med %>% 
  select(Year, Title) %>% 
  group_by(Year, Title) %>% 
  summarize(Count = n()) 
  mutate(Year_percent = Title)
ye


yb <- ggplot(year_count, aes(x=Year, y = Count, width = .7)) + geom_bar(stat = "identity", fill = "green", position = "identity") + theme_classic() + theme(axis.line = element_line(size = 0.2, 
    linetype = "solid"), axis.ticks = element_line(colour = "black"), 
    panel.grid.major = element_line(colour = NA), 
    panel.grid.minor = element_line(colour = NA), 
    axis.text = element_text(size = 12, colour = "black"), 
    panel.background = element_rect(fill = NA), 
    plot.background = element_rect(colour = NA), 
    legend.position = "none") +labs(x = NULL, y = NULL) + 
  theme(axis.text.x = element_text(angle = 45)) +
  theme(axis.text.x = element_text(vjust = 0.5))
yb


```

